enum ActionTypes {
    TOGGLE_MODAL = 'TOGGLE_MODAL',
    FETCH_IMAGES = 'FETCH_IMAGES',
    FETCH_IMAGES_INIT = 'FETCH_IMAGES_INIT',
    FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS',
    FETCH_IMAGES_FAIL = 'FETCH_IMAGES_FAIL',
    FILE_DROP = 'FILE_DROP',
    REMOVE_IMAGE_INIT = 'REMOVE_IMAGE_INIT',
    REMOVE_IMAGE_START = 'REMOVE_IMAGE_START',
    REMOVE_IMAGE_FAIL = 'REMOVE_IMAGE_FAIL',
    REMOVE_IMAGE_SUCCESS = 'REMOVE_IMAGE_SUCCESS',
}
export default ActionTypes;