enum ActionTypes {
    TOGGLE_MODAL = 'TOGGLE_MODAL',
    FETCH_IMAGES = 'FETCH_IMAGES',
    FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS',
    FETCH_IMAGES_FAIL = 'FETCH_IMAGES_FAIL',
}
export default ActionTypes;